const ENDPOINT="https://formspree.io/f/xvkgldlb";const $=id=>document.getElementById(id);const pages=[$("page1"),$("page2"),$("page3"),$("page4"),$("page5")];let place="",activity="",date="",time="",timer;
function moveNo(){const a=$("buttons").getBoundingClientRect(),b=$("no"),pad=8;b.style.left=(pad+Math.random()*Math.max(a.width-b.offsetWidth-pad*2,1))+"px";b.style.top=(pad+Math.random()*Math.max(a.height-b.offsetHeight-pad*2,1))+"px";b.style.transform="none"}
function show(n){pages.forEach((p,i)=>p.classList.toggle("hidden",i!==n))}
$("yes").onclick=()=>{clearInterval(timer);show(1)};setTimeout(moveNo,500);timer=setInterval(moveNo,1900);$("no").onmouseenter=moveNo;$("no").ontouchstart=e=>{e.preventDefault();moveNo()};
$("dateNext").onclick=()=>{if(!$("date").value||!$("time").value)return alert("Please pick a date and time! 🥺");date=new Date($("date").value+"T00:00:00");time=$("time").value;show(2)};
document.querySelectorAll("#locations button").forEach(b=>b.onclick=()=>{document.querySelectorAll("#locations button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");place=b.dataset.place});
$("placeNext").onclick=()=>place?show(3):alert("Please pick a place! 🥺");
document.querySelectorAll("#activities button").forEach(b=>b.onclick=()=>{document.querySelectorAll("#activities button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");activity=b.dataset.activity});
function ft(t){let [h,m]=t.split(":");h=+h;let ap=h>=12?"PM":"AM";h=h%12||12;return `${h}:${m} ${ap}`}
$("send").onclick=async()=>{if(!activity)return alert("Please pick something! 🥺");let d=date.toLocaleDateString("en-US",{weekday:"long",year:"numeric",month:"long",day:"numeric"}),t=ft(time),btn=$("send");btn.disabled=true;btn.textContent="Sending... 💌";try{let r=await fetch(ENDPOINT,{method:"POST",headers:{"Accept":"application/json","Content-Type":"application/json"},body:JSON.stringify({_subject:"💌 Dr. Tommy accepted the date invitation!",name:"Dr. Tommy",date:d,time:t,location:place,activity})});if(!r.ok)throw Error();$("final").innerHTML=`📅 <strong>${d}</strong><br><br>🕐 <strong>${t}</strong><br><br>📍 <strong>${place}</strong><br><br>✨ <strong>${activity}</strong>`;show(4)}catch(e){alert("Oops! Something went wrong. Please try again. 🥺");btn.disabled=false;btn.textContent="Send it to Six 💌"}};
